const primaryPermissions = {
	super: 'SUPER',
	user: 'USER',
	rol: 'ROL',
	audit: 'AUDIT',
	company: 'COMPANY',
	system: 'SYSTEM',
	subscription: 'SUBSCRIPTION',
	payment: 'PAYMENT',
};

const permissions = {
	super: primaryPermissions.super,
	user: primaryPermissions.user,
	userProfile: `${primaryPermissions.user}_PROFILE`,
	userAdd: `${primaryPermissions.user}_ADD`,
	userRead: `${primaryPermissions.user}_READ`,
	userReadOne: `${primaryPermissions.user}_READ_ONE`,
	userUpdate: `${primaryPermissions.user}_UPDATE`,
	userDelete: `${primaryPermissions.user}_DELETE`,
	rol: primaryPermissions.rol,
	rolAdd: `${primaryPermissions.rol}_ADD`,
	rolRead: `${primaryPermissions.rol}_READ`,
	rolReadOne: `${primaryPermissions.rol}_READ_ONE`,
	rolUpdate: `${primaryPermissions.rol}_UPDATE`,
	rolDelete: `${primaryPermissions.rol}_DELETE`,
	audit: primaryPermissions.audit,
	auditRead: `${primaryPermissions.audit}_READ`,
	auditDelete: `${primaryPermissions.audit}_DELETE`,
	company: primaryPermissions.company,
	companyAdd: `${primaryPermissions.company}_ADD`,
	companyRead: `${primaryPermissions.company}_READ`,
	companyReadOne: `${primaryPermissions.company}_READ_ONE`,
	companyUpdate: `${primaryPermissions.company}_UPDATE`,
	companyDelete: `${primaryPermissions.company}_DELETE`,
	system: primaryPermissions.system,
	systemAdd: `${primaryPermissions.system}_ADD`,
	systemRead: `${primaryPermissions.system}_READ`,
	systemReadOne: `${primaryPermissions.system}_READ_ONE`,
	systemUpdate: `${primaryPermissions.system}_UPDATE`,
	systemDelete: `${primaryPermissions.system}_DELETE`,
	subscription: primaryPermissions.subscription,
	subscriptionAdd: `${primaryPermissions.subscription}_ADD`,
	subscriptionRead: `${primaryPermissions.subscription}_READ`,
	subscriptionReadOne: `${primaryPermissions.subscription}_READ_ONE`,
	subscriptionUpdate: `${primaryPermissions.subscription}_UPDATE`,
	subscriptionDelete: `${primaryPermissions.subscription}_DELETE`,
	payment: primaryPermissions.payment,
	paymentAdd: `${primaryPermissions.payment}_ADD`,
	paymentRead: `${primaryPermissions.payment}_READ`,
	paymentReadOne: `${primaryPermissions.payment}_READ_ONE`,
	paymentUpdate: `${primaryPermissions.payment}_UPDATE`,
	paymentDelete: `${primaryPermissions.payment}_DELETE`,
} as const;

export const textPermission: Record<string, string> = {
	[permissions.super]: 'Super usuario',
	[permissions.user]: 'Usuario',
	[`${primaryPermissions.user}_PROFILE`]: 'Perfil de usuario',
	[`${primaryPermissions.user}_ADD`]: 'Agregar usuario',
	[`${primaryPermissions.user}_READ`]: 'Leer usuario',
	[`${primaryPermissions.user}_READ_ONE`]: 'Leer usuario específico',
	[`${primaryPermissions.user}_UPDATE`]: 'Actualizar usuario',
	[`${primaryPermissions.user}_DELETE`]: 'Eliminar usuario',
	[permissions.rol]: 'Rol',
	[`${primaryPermissions.rol}_ADD`]: 'Agregar rol',
	[`${primaryPermissions.rol}_READ`]: 'Leer rol',
	[`${primaryPermissions.rol}_READ_ONE`]: 'Leer rol específico',
	[`${primaryPermissions.rol}_UPDATE`]: 'Actualizar rol',
	[`${primaryPermissions.rol}_DELETE`]: 'Eliminar rol',
	[permissions.audit]: 'Auditoría',
	[`${primaryPermissions.audit}_READ`]: 'Leer auditoría',
	[`${primaryPermissions.audit}_DELETE`]: 'Eliminar auditoría',
	[permissions.company]: 'Empresa',
	[`${primaryPermissions.company}_ADD`]: 'Agregar empresa',
	[`${primaryPermissions.company}_READ`]: 'Leer empresa',
	[`${primaryPermissions.company}_READ_ONE`]: 'Leer empresa específica',
	[`${primaryPermissions.company}_UPDATE`]: 'Actualizar empresa',
	[`${primaryPermissions.company}_DELETE`]: 'Eliminar empresa',
	[permissions.system]: 'Sistema',
	[`${primaryPermissions.system}_ADD`]: 'Agregar sistema',
	[`${primaryPermissions.system}_READ`]: 'Leer sistema',
	[`${primaryPermissions.system}_READ_ONE`]: 'Leer sistema específico',
	[`${primaryPermissions.system}_UPDATE`]: 'Actualizar sistema',
	[`${primaryPermissions.system}_DELETE`]: 'Eliminar sistema',
	[permissions.subscription]: 'Suscripción',
	[`${primaryPermissions.subscription}_ADD`]: 'Agregar suscripción',
	[`${primaryPermissions.subscription}_READ`]: 'Leer suscripción',
	[`${primaryPermissions.subscription}_READ_ONE`]:
		'Leer suscripción específica',
	[`${primaryPermissions.subscription}_UPDATE`]: 'Actualizar suscripción',
	[`${primaryPermissions.subscription}_DELETE`]: 'Eliminar suscripción',
	[permissions.payment]: 'Pago',
	[`${primaryPermissions.payment}_ADD`]: 'Agregar pago',
	[`${primaryPermissions.payment}_READ`]: 'Leer pago',
	[`${primaryPermissions.payment}_READ_ONE`]: 'Leer pago específico',
	[`${primaryPermissions.payment}_UPDATE`]: 'Actualizar pago',
	[`${primaryPermissions.payment}_DELETE`]: 'Eliminar pago',
};

export { permissions as Permission };
