services:
  app:
    build:
      context: .
      target: ${NODE_ENV:-development}
      args:
        - NODE_ENV=${NODE_ENV:-development}
    container_name: reactvite_${NODE_ENV:-development}
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - NODE_ENV=${NODE_ENV:-development}
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
