const primaryPermissions = {
	super: 'SUPER',
	user: 'USER',
	rol: 'ROL',
	audit: 'AUDIT',
	company: 'COMPANY',
	system: 'SYSTEM',
	subscription: 'SUBSCRIPTION',
	payment: 'PAYMENT',
	paymentMethod: 'PAYMENTMETHOD',
	language: 'LANGUAGE',
	companySyste: 'COMPANYSYSTE',
	companyRequest: 'COMPANYREQUEST',
	historyPayment: 'HISTORYPAYMENT',
	notification: 'NOTIFICATION',
	dashboard: 'DASHBOARD',
	plan: 'PLAN',
};

const permissions = {
	super: primaryPermissions.super,
	user: primaryPermissions.user,
	userProfile: `${primaryPermissions.user}_PROFILE`,
	userAdd: `${primaryPermissions.user}_ADD`,
	userRead: `${primaryPermissions.user}_READ`,
	userReadOne: `${primaryPermissions.user}_READ_ONE`,
	userUpdate: `${primaryPermissions.user}_UPDATE`,
	userDelete: `${primaryPermissions.user}_DELETE`,
	rol: primaryPermissions.rol,
	rolAdd: `${primaryPermissions.rol}_ADD`,
	rolRead: `${primaryPermissions.rol}_READ`,
	rolReadOne: `${primaryPermissions.rol}_READ_ONE`,
	rolUpdate: `${primaryPermissions.rol}_UPDATE`,
	rolDelete: `${primaryPermissions.rol}_DELETE`,
	audit: primaryPermissions.audit,
	auditRead: `${primaryPermissions.audit}_READ`,
	auditDelete: `${primaryPermissions.audit}_DELETE`,
	company: primaryPermissions.company,
	companyAdd: `${primaryPermissions.company}_ADD`,
	companyRead: `${primaryPermissions.company}_READ`,
	companyReadOne: `${primaryPermissions.company}_READ_ONE`,
	companyUpdate: `${primaryPermissions.company}_UPDATE`,
	companyDelete: `${primaryPermissions.company}_DELETE`,
	system: primaryPermissions.system,
	systemAdd: `${primaryPermissions.system}_ADD`,
	systemRead: `${primaryPermissions.system}_READ`,
	systemReadOne: `${primaryPermissions.system}_READ_ONE`,
	systemUpdate: `${primaryPermissions.system}_UPDATE`,
	systemDelete: `${primaryPermissions.system}_DELETE`,
	subscription: primaryPermissions.subscription,
	subscriptionAdd: `${primaryPermissions.subscription}_ADD`,
	subscriptionRead: `${primaryPermissions.subscription}_READ`,
	subscriptionReadOne: `${primaryPermissions.subscription}_READ_ONE`,
	subscriptionUpdate: `${primaryPermissions.subscription}_UPDATE`,
	subscriptionDelete: `${primaryPermissions.subscription}_DELETE`,
	payment: primaryPermissions.payment,
	paymentAdd: `${primaryPermissions.payment}_ADD`,
	paymentRead: `${primaryPermissions.payment}_READ`,
	paymentReadOne: `${primaryPermissions.payment}_READ_ONE`,
	paymentUpdate: `${primaryPermissions.payment}_UPDATE`,
	paymentDelete: `${primaryPermissions.payment}_DELETE`,
	paymentMethod: primaryPermissions.paymentMethod,
	paymentMethodAdd: `${primaryPermissions.paymentMethod}_ADD`,
	paymentMethodRead: `${primaryPermissions.paymentMethod}_READ`,
	paymentMethodReadOne: `${primaryPermissions.paymentMethod}_READ_ONE`,
	paymentMethodUpdate: `${primaryPermissions.paymentMethod}_UPDATE`,
	paymentMethodDelete: `${primaryPermissions.paymentMethod}_DELETE`,
	language: primaryPermissions.language,
	languageAdd: `${primaryPermissions.language}_ADD`,
	languageRead: `${primaryPermissions.language}_READ`,
	languageReadOne: `${primaryPermissions.language}_READ_ONE`,
	languageUpdate: `${primaryPermissions.language}_UPDATE`,
	languageDelete: `${primaryPermissions.language}_DELETE`,
	companySyste: primaryPermissions.companySyste,
	companySysteAdd: `${primaryPermissions.companySyste}_ADD`,
	companySysteRead: `${primaryPermissions.companySyste}_READ`,
	companySysteReadOne: `${primaryPermissions.companySyste}_READ_ONE`,
	companySysteUpdate: `${primaryPermissions.companySyste}_UPDATE`,
	companySysteDelete: `${primaryPermissions.companySyste}_DELETE`,
	companyRequest: primaryPermissions.companyRequest,
	companyRequestAdd: `${primaryPermissions.companyRequest}_ADD`,
	companyRequestRead: `${primaryPermissions.companyRequest}_READ`,
	companyRequestReadOne: `${primaryPermissions.companyRequest}_READ_ONE`,
	companyRequestUpdate: `${primaryPermissions.companyRequest}_UPDATE`,
	companyRequestDelete: `${primaryPermissions.companyRequest}_DELETE`,
	historyPayment: primaryPermissions.historyPayment,
	historyPaymentAdd: `${primaryPermissions.historyPayment}_ADD`,
	historyPaymentRead: `${primaryPermissions.historyPayment}_READ`,
	historyPaymentReadOne: `${primaryPermissions.historyPayment}_READ_ONE`,
	historyPaymentUpdate: `${primaryPermissions.historyPayment}_UPDATE`,
	historyPaymentDelete: `${primaryPermissions.historyPayment}_DELETE`,
	notification: primaryPermissions.notification,
	notificationAdd: `${primaryPermissions.notification}_ADD`,
	notificationRead: `${primaryPermissions.notification}_READ`,
	notificationReadOne: `${primaryPermissions.notification}_READ_ONE`,
	notificationUpdate: `${primaryPermissions.notification}_UPDATE`,
	notificationDelete: `${primaryPermissions.notification}_DELETE`,
	notificationPaymentFailed: `${primaryPermissions.notification}_PAYMENT_FAILED`,
	notificationPaymentSuccess: `${primaryPermissions.notification}_PAYMENT_SUCCESS`,
	notificationPaymentOverdue: `${primaryPermissions.notification}_PAYMENT_OVERDUE`,
	notificationServerConnected: `${primaryPermissions.notification}_SERVER_CONNECTED`,
	notificationServerDisconnected: `${primaryPermissions.notification}_SERVER_DISCONNECTED`,
	notificationSystemAlert: `${primaryPermissions.notification}_SYSTEM_ALERT`,
	dashboard: primaryPermissions.dashboard,
	dashboardRead: `${primaryPermissions.dashboard}_READ`,
	plan: primaryPermissions.plan,
	planAdd: `${primaryPermissions.plan}_ADD`,
	planRead: `${primaryPermissions.plan}_READ`,
	planReadOne: `${primaryPermissions.plan}_READ_ONE`,
	planUpdate: `${primaryPermissions.plan}_UPDATE`,
	planDelete: `${primaryPermissions.plan}_DELETE`,
} as const;

export const textPermission: Record<string, string> = {
	[permissions.super]: 'Super usuario',
	[permissions.user]: 'Usuario',
	[`${primaryPermissions.user}_PROFILE`]: 'Perfil de usuario',
	[`${primaryPermissions.user}_ADD`]: 'Agregar usuario',
	[`${primaryPermissions.user}_READ`]: 'Leer usuario',
	[`${primaryPermissions.user}_READ_ONE`]: 'Leer usuario específico',
	[`${primaryPermissions.user}_UPDATE`]: 'Actualizar usuario',
	[`${primaryPermissions.user}_DELETE`]: 'Eliminar usuario',
	[permissions.rol]: 'Rol',
	[`${primaryPermissions.rol}_ADD`]: 'Agregar rol',
	[`${primaryPermissions.rol}_READ`]: 'Leer rol',
	[`${primaryPermissions.rol}_READ_ONE`]: 'Leer rol específico',
	[`${primaryPermissions.rol}_UPDATE`]: 'Actualizar rol',
	[`${primaryPermissions.rol}_DELETE`]: 'Eliminar rol',
	[permissions.audit]: 'Auditoría',
	[`${primaryPermissions.audit}_READ`]: 'Leer auditoría',
	[`${primaryPermissions.audit}_DELETE`]: 'Eliminar auditoría',
	[permissions.company]: 'Empresa',
	[`${primaryPermissions.company}_ADD`]: 'Agregar empresa',
	[`${primaryPermissions.company}_READ`]: 'Leer empresa',
	[`${primaryPermissions.company}_READ_ONE`]: 'Leer empresa específica',
	[`${primaryPermissions.company}_UPDATE`]: 'Actualizar empresa',
	[`${primaryPermissions.company}_DELETE`]: 'Eliminar empresa',
	[permissions.system]: 'Sistema',
	[`${primaryPermissions.system}_ADD`]: 'Agregar sistema',
	[`${primaryPermissions.system}_READ`]: 'Leer sistema',
	[`${primaryPermissions.system}_READ_ONE`]: 'Leer sistema específico',
	[`${primaryPermissions.system}_UPDATE`]: 'Actualizar sistema',
	[`${primaryPermissions.system}_DELETE`]: 'Eliminar sistema',
	[permissions.subscription]: 'Suscripción',
	[`${primaryPermissions.subscription}_ADD`]: 'Agregar suscripción',
	[`${primaryPermissions.subscription}_READ`]: 'Leer suscripción',
	[`${primaryPermissions.subscription}_READ_ONE`]:
		'Leer suscripción específica',
	[`${primaryPermissions.subscription}_UPDATE`]: 'Actualizar suscripción',
	[`${primaryPermissions.subscription}_DELETE`]: 'Eliminar suscripción',
	[permissions.payment]: 'Pago',
	[`${primaryPermissions.payment}_ADD`]: 'Agregar pago',
	[`${primaryPermissions.payment}_READ`]: 'Leer pago',
	[`${primaryPermissions.payment}_READ_ONE`]: 'Leer pago específico',
	[`${primaryPermissions.payment}_UPDATE`]: 'Actualizar pago',
	[`${primaryPermissions.payment}_DELETE`]: 'Eliminar pago',
	[permissions.paymentMethod]: 'Método de pago',
	[`${primaryPermissions.paymentMethod}_ADD`]: 'Agregar método de pago',
	[`${primaryPermissions.paymentMethod}_READ`]: 'Leer método de pago',
	[`${primaryPermissions.paymentMethod}_READ_ONE`]:
		'Leer método de pago específico',
	[`${primaryPermissions.paymentMethod}_UPDATE`]: 'Actualizar método de pago',
	[`${primaryPermissions.paymentMethod}_DELETE`]: 'Eliminar método de pago',
	[permissions.language]: 'Idioma',
	[`${primaryPermissions.language}_ADD`]: 'Agregar idioma',
	[`${primaryPermissions.language}_READ`]: 'Leer idioma',
	[`${primaryPermissions.language}_READ_ONE`]: 'Leer idioma específico',
	[`${primaryPermissions.language}_UPDATE`]: 'Actualizar idioma',
	[`${primaryPermissions.language}_DELETE`]: 'Eliminar idioma',
	[permissions.companySyste]: 'Sistema de empresa',
	[`${primaryPermissions.companySyste}_ADD`]: 'Agregar sistema de empresa',
	[`${primaryPermissions.companySyste}_READ`]: 'Leer sistema de empresa',
	[`${primaryPermissions.companySyste}_READ_ONE`]:
		'Leer sistema de empresa específico',
	[`${primaryPermissions.companySyste}_UPDATE`]:
		'Actualizar sistema de empresa',
	[`${primaryPermissions.companySyste}_DELETE`]: 'Eliminar sistema de empresa',
	[permissions.companyRequest]: 'Solicitud de empresa',
	[`${primaryPermissions.companyRequest}_ADD`]: 'Agregar solicitud de empresa',
	[`${primaryPermissions.companyRequest}_READ`]: 'Leer solicitud de empresa',
	[`${primaryPermissions.companyRequest}_READ_ONE`]:
		'Leer solicitud de empresa específica',
	[`${primaryPermissions.companyRequest}_UPDATE`]:
		'Actualizar solicitud de empresa',
	[`${primaryPermissions.companyRequest}_DELETE`]:
		'Eliminar solicitud de empresa',
	[permissions.historyPayment]: 'Historial de pago',
	[`${primaryPermissions.historyPayment}_ADD`]: 'Agregar historial de pago',
	[`${primaryPermissions.historyPayment}_READ`]: 'Leer historial de pago',
	[`${primaryPermissions.historyPayment}_READ_ONE`]:
		'Leer historial de pago específico',
	[`${primaryPermissions.historyPayment}_UPDATE`]:
		'Actualizar historial de pago',
	[`${primaryPermissions.historyPayment}_DELETE`]: 'Eliminar historial de pago',
	[permissions.notification]: 'Notificación',
	[`${primaryPermissions.notification}_ADD`]: 'Agregar notificación',
	[`${primaryPermissions.notification}_READ`]: 'Leer notificación',
	[`${primaryPermissions.notification}_READ_ONE`]:
		'Leer notificación específica',
	[`${primaryPermissions.notification}_UPDATE`]: 'Actualizar notificación',
	[`${primaryPermissions.notification}_DELETE`]: 'Eliminar notificación',
	[`${primaryPermissions.notification}_PAYMENT_FAILED`]:
		'Notificación de pago fallido',
	[`${primaryPermissions.notification}_PAYMENT_SUCCESS`]:
		'Notificación de pago exitoso',
	[`${primaryPermissions.notification}_PAYMENT_OVERDUE`]:
		'Notificación de pago vencido',
	[`${primaryPermissions.notification}_SERVER_CONNECTED`]:
		'Notificación de servidor conectado',
	[`${primaryPermissions.notification}_SERVER_DISCONNECTED`]:
		'Notificación de servidor desconectado',
	[`${primaryPermissions.notification}_SYSTEM_ALERT`]: 'Alerta del sistema',
	[permissions.dashboard]: 'Dashboard',
	[`${primaryPermissions.dashboard}_READ`]: 'Leer dashboard',
	[permissions.plan]: 'Plan',
	[`${primaryPermissions.plan}_ADD`]: 'Agregar plan',
	[`${primaryPermissions.plan}_READ`]: 'Leer plan',
	[`${primaryPermissions.plan}_READ_ONE`]: 'Leer plan específico',
	[`${primaryPermissions.plan}_UPDATE`]: 'Actualizar plan',
	[`${primaryPermissions.plan}_DELETE`]: 'Eliminar plan',
};

export { permissions as Permission };
