const modules = {
	auth: '/auth',
	user: '/user',
	rol: '/rol',
	audit: '/audit',
	system: '/system',
	language: '/language',
	plan: '/plan',
	company: '/company',
	companySyste: '/companySyste',
	companyRequest: '/companyRequest',
	paymentMethod: '/paymentMethod',
	payments: '/payments',
	historyPayment: '/historyPayment',
	notification: '/notification',
	dashboard: '/dashboard',
};

export const routes = {
	login: `${modules.auth}/login`,
	logout: `${modules.auth}/logout`,
	refreshToken: `${modules.auth}/refresh-token`,
	check: `${modules.auth}/check-session`,
	rol: {
		base: modules.rol,
		one: `${modules.rol}/one/:uid`,
		per: `${modules.rol}/per`,
		all: `${modules.rol}/all`,
		delete: `${modules.rol}/delete/:uid`,
	},
	user: {
		base: modules.user,
		one: `${modules.user}/one/:uid`,
		create: `${modules.user}/protect`,
		profile: `${modules.user}/profile`,
		profileData: `${modules.user}/profile/data`,
		profileEmail: `${modules.user}/profile/email`,
		profilePassword: `${modules.user}/profile/password`,
		profileUnregister: `${modules.user}/profile/unregister`,
		delete: `${modules.user}/delete/:uid`,
	},
	audit: {
		base: modules.audit,
		delete: `${modules.audit}/delete/:uid`,
	},
	system: {
		base: modules.system,
		one: `${modules.system}/one/:uid`,
		all: `${modules.system}/all`,
		delete: `${modules.system}/delete/:uid`,
	},
	language: {
		base: modules.language,
		one: `${modules.language}/one/:uid`,
		all: `${modules.language}/all`,
		delete: `${modules.language}/delete/:uid`,
	},
	plan: {
		base: modules.plan,
		one: `${modules.plan}/one/:uid`,
		all: `${modules.plan}/all`,
		delete: `${modules.plan}/delete/:uid`,
	},
	company: {
		base: modules.company,
		one: `${modules.company}/one/:uid`,
		all: `${modules.company}/all`,
		delete: `${modules.company}/delete/:uid`,
	},
	companySyste: {
		base: modules.companySyste,
		one: `${modules.companySyste}/one/:uid`,
		all: `${modules.companySyste}/all`,
		delete: `${modules.companySyste}/delete/:uid`,
		checkServer: `${modules.companySyste}/check-server/:uid`,
	},
	companyRequest: {
		base: modules.companyRequest,
		one: `${modules.companyRequest}/one/:uid`,
		all: `${modules.companyRequest}/all`,
		delete: `${modules.companyRequest}/delete/:uid`,
	},
	paymentMethod: {
		base: modules.paymentMethod,
		one: `${modules.paymentMethod}/one/:uid`,
		all: `${modules.paymentMethod}/all`,
		delete: `${modules.paymentMethod}/delete/:uid`,
	},
	payments: {
		base: modules.payments,
		one: `${modules.payments}/one/:uid`,
		all: `${modules.payments}/all`,
		delete: `${modules.payments}/delete/:uid`,
	},
	historyPayment: {
		base: modules.historyPayment,
		one: `${modules.historyPayment}/one/:uid`,
		all: `${modules.historyPayment}/all`,
		delete: `${modules.historyPayment}/delete/:uid`,
	},
	notification: {
		base: modules.notification,
		one: `${modules.notification}/one/:uid`,
		all: `${modules.notification}/all`,
		read: `${modules.notification}/read/:uid`,
		delete: `${modules.notification}/delete/:uid`,
	},
	dashboard: modules.dashboard,
};